source 'https://rubygems.org'

gem 'activerecord'
gem 'activerecord-import'
gem 'bcrypt'
gem 'byebug'
gem 'dotenv'
gem 'faker'
gem 'minitest'
gem 'redis'
gem 'pg'
gem 'puma'
gem 'rake'
gem 'newrelic_rpm'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-flash'
